language: node_js
node_js:
    - 12
    - 10
    - 8

matrix:
    allow_failures:
        - os: windows
        - node_js: 12

os:
    - linux
    - osx
    - windows

script:
  - npm run lint && npm run build && npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: required

services:
  - docker

deploy:
    provider: script
    script: npm run docker-ci
    skip_cleanup: true
    on:
        node: '8'
        condition: $TRAVIS_OS_NAME = linux
        tags: true
        all_branches: false

